### ISSUE TITLE
Send "Content-Length" header field

### ISSUE THREAD

**Issue by EvgeniyDoctor** [MyLittleWallpaper/MyLittleWallpaper#37]
Hello.
I noticed that the server does not send the length of the file. Is there a reason for this?

I need the file length because I have an Android app and I'd like to add a progress bar when the user download an image. But I can't do that without knowing the length of the file.

For example, I made this request to download an image: [https://www.mylittlewallpaper.com/images/o_4fcee28adabac4.99739877.png](https://www.mylittlewallpaper.com/images/o_4fcee28adabac4.99739877.png)
but there is no `"Content-Length"` header field.

So, should I wait for this header field to be added?

**Comment by SharkMachine** [comment]
Content length header is now there.
